package uk.co.gmillns.pad13photobooth;

import android.Manifest; import android.content.*; import android.content.pm.PackageManager; import android.graphics.*; import android.graphics.drawable.ColorDrawable; import android.net.Uri; import android.os.*; import android.provider.MediaStore; import android.view.*; import android.widget.*;
import androidx.activity.result.ActivityResultLauncher; import androidx.activity.result.contract.ActivityResultContracts; import androidx.annotation.NonNull; import androidx.appcompat.app.AppCompatActivity; import androidx.camera.core.*; import androidx.camera.lifecycle.ProcessCameraProvider; import androidx.camera.view.PreviewView; import androidx.core.content.ContextCompat;
import com.google.common.util.concurrent.ListenableFuture; import java.io.*; import java.text.SimpleDateFormat; import java.util.*;

public class MainActivity extends AppCompatActivity {
 private PreviewView previewView; private ImageView photoPreview,entryPhoto; private TextView countdown,message; private LinearLayout cameraControls,reviewControls,thumbStrip; private View flash,cameraScreen,homeScreen,writeScreen,viewerScreen; private ImageCapture imageCapture; private File pendingPhoto; private final Handler handler=new Handler(Looper.getMainLooper()); private DrawingView drawing; private EditText typedMessage,guestNames; private boolean typing=false; private File originalsDir,pagesDir; private int viewingIndex=0; private ArrayList<File> pages=new ArrayList<>();
 private final ActivityResultLauncher<String> cameraPermission=registerForActivityResult(new ActivityResultContracts.RequestPermission(),g->{if(g)startCamera();else Toast.makeText(this,"Camera permission is required.",Toast.LENGTH_LONG).show();});
 @Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);hideSystemUi(); originalsDir=new File(getExternalFilesDir(null),"WeddingGuestbook/OriginalPhotos"); pagesDir=new File(getExternalFilesDir(null),"WeddingGuestbook/Pages"); originalsDir.mkdirs();pagesDir.mkdirs(); bind(); refreshEntries(); showHome(); if(ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)startCamera();else cameraPermission.launch(Manifest.permission.CAMERA);}
 private void bind(){
  homeScreen=findViewById(R.id.homeScreen);cameraScreen=findViewById(R.id.cameraScreen);writeScreen=findViewById(R.id.writeScreen);viewerScreen=findViewById(R.id.viewerScreen);thumbStrip=findViewById(R.id.thumbStrip);
  previewView=findViewById(R.id.previewView);previewView.setScaleType(PreviewView.ScaleType.FILL_CENTER);photoPreview=findViewById(R.id.photoPreview);entryPhoto=findViewById(R.id.entryPhoto);countdown=findViewById(R.id.countdown);message=findViewById(R.id.message);cameraControls=findViewById(R.id.cameraControls);reviewControls=findViewById(R.id.reviewControls);flash=findViewById(R.id.flash);drawing=findViewById(R.id.drawing);typedMessage=findViewById(R.id.typedMessage);guestNames=findViewById(R.id.guestNames);
  findViewById(R.id.addEntry).setOnClickListener(v->showCamera());findViewById(R.id.takePhoto).setOnClickListener(v->beginCountdown());findViewById(R.id.retake).setOnClickListener(v->resetToCamera());findViewById(R.id.keep).setOnClickListener(v->showWrite());findViewById(R.id.undo).setOnClickListener(v->drawing.undo());findViewById(R.id.clear).setOnClickListener(v->drawing.clearAll());findViewById(R.id.eraser).setOnClickListener(v->{drawing.setEraser(true);Toast.makeText(this,"Eraser on — tap a stroke to remove it",Toast.LENGTH_SHORT).show();});findViewById(R.id.pen).setOnClickListener(v->drawing.setEraser(false));findViewById(R.id.typeToggle).setOnClickListener(v->toggleTyping());findViewById(R.id.saveEntry).setOnClickListener(v->saveEntry());findViewById(R.id.cancelEntry).setOnClickListener(v->{discardPending();showHome();});findViewById(R.id.viewerBack).setOnClickListener(v->showHome());findViewById(R.id.prevEntry).setOnClickListener(v->showViewer(Math.max(0,viewingIndex-1)));findViewById(R.id.nextEntry).setOnClickListener(v->showViewer(Math.min(pages.size()-1,viewingIndex+1)));
 }
 private void showOnly(View v){homeScreen.setVisibility(View.GONE);cameraScreen.setVisibility(View.GONE);writeScreen.setVisibility(View.GONE);viewerScreen.setVisibility(View.GONE);v.setVisibility(View.VISIBLE);hideSystemUi();}
 private void showHome(){refreshEntries();showOnly(homeScreen);}
 private void showCamera(){showOnly(cameraScreen);resetToCamera();}
 private void showWrite(){if(pendingPhoto==null)return; showOnly(writeScreen);entryPhoto.setImageURI(Uri.fromFile(pendingPhoto));drawing.clearAll();typedMessage.setText("");guestNames.setText("");typing=false;typedMessage.setVisibility(View.GONE);drawing.setVisibility(View.VISIBLE);}
 private void toggleTyping(){typing=!typing;typedMessage.setVisibility(typing?View.VISIBLE:View.GONE);drawing.setVisibility(typing?View.GONE:View.VISIBLE);}
 private void startCamera(){ListenableFuture<ProcessCameraProvider> f=ProcessCameraProvider.getInstance(this);f.addListener(()->{try{ProcessCameraProvider p=f.get();Preview pr=new Preview.Builder().build();pr.setSurfaceProvider(previewView.getSurfaceProvider());imageCapture=new ImageCapture.Builder().setCaptureMode(ImageCapture.CAPTURE_MODE_MAXIMIZE_QUALITY).build();p.unbindAll();CameraSelector s=p.hasCamera(CameraSelector.DEFAULT_FRONT_CAMERA)?CameraSelector.DEFAULT_FRONT_CAMERA:CameraSelector.DEFAULT_BACK_CAMERA;p.bindToLifecycle(this,s,pr,imageCapture);}catch(Exception e){Toast.makeText(this,"Unable to start camera: "+e.getMessage(),Toast.LENGTH_LONG).show();}},ContextCompat.getMainExecutor(this));}
 private void beginCountdown(){cameraControls.setVisibility(View.GONE);countdown.setVisibility(View.VISIBLE);showCount(3);}
 private void showCount(int n){if(n==0){countdown.setVisibility(View.GONE);flash.setVisibility(View.VISIBLE);flash.setAlpha(1f);flash.animate().alpha(0f).setDuration(220).withEndAction(()->flash.setVisibility(View.GONE)).start();capturePhoto();return;}countdown.setText(String.valueOf(n));handler.postDelayed(()->showCount(n-1),850);}
 private void capturePhoto(){if(imageCapture==null){resetToCamera();return;}pendingPhoto=new File(getCacheDir(),"wedding_"+System.currentTimeMillis()+".jpg");ImageCapture.OutputFileOptions o=new ImageCapture.OutputFileOptions.Builder(pendingPhoto).build();imageCapture.takePicture(o,ContextCompat.getMainExecutor(this),new ImageCapture.OnImageSavedCallback(){public void onImageSaved(@NonNull ImageCapture.OutputFileResults r){photoPreview.setImageURI(Uri.fromFile(pendingPhoto));photoPreview.setVisibility(View.VISIBLE);previewView.setVisibility(View.GONE);reviewControls.setVisibility(View.VISIBLE);}public void onError(@NonNull ImageCaptureException e){Toast.makeText(MainActivity.this,"Photo failed: "+e.getMessage(),Toast.LENGTH_LONG).show();resetToCamera();}});}
 private void saveEntry(){if(pendingPhoto==null||!pendingPhoto.exists())return; String names=guestNames.getText().toString().trim(); if(names.isEmpty())names="Our Wedding Guests"; try{String stamp=new SimpleDateFormat("yyyyMMdd_HHmmss",Locale.UK).format(new Date());File original=new File(originalsDir,"WeddingPhoto_"+stamp+".jpg");copy(pendingPhoto,original);Bitmap photo=BitmapFactory.decodeFile(pendingPhoto.getAbsolutePath());Bitmap msgBmp=null;String typed=typedMessage.getText().toString().trim();if(!typing && !drawing.isEmpty())msgBmp=drawing.snapshot();Bitmap page=composePage(photo,msgBmp,typed,names);File pageFile=new File(pagesDir,"Guestbook_"+stamp+".jpg");try(FileOutputStream out=new FileOutputStream(pageFile)){page.compress(Bitmap.CompressFormat.JPEG,94,out);}saveToGallery(pageFile,"GarryKarenGuestbook_"+stamp+".jpg");discardPending();message.setText("THANK YOU!\nYour message is now in our guestbook ♥");message.setVisibility(View.VISIBLE);showOnly(homeScreen);refreshEntries();handler.postDelayed(()->message.setVisibility(View.GONE),2800);}catch(Exception e){Toast.makeText(this,"Could not save entry: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
 private Bitmap composePage(Bitmap photo,Bitmap handwriting,String typed,String names){int W=1600,H=1200;Bitmap out=Bitmap.createBitmap(W,H,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(out);c.drawColor(Color.rgb(255,253,247));Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);p.setColor(Color.rgb(18,40,92));p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.create("serif",Typeface.BOLD));p.setTextSize(62);c.drawText("Garry & Karen",W/2,75,p);p.setTextSize(28);p.setTypeface(Typeface.create("sans",Typeface.NORMAL));c.drawText("OUR WEDDING GUESTBOOK  •  30 DECEMBER 2026",W/2,118,p);Rect src=new Rect(0,0,photo.getWidth(),photo.getHeight());Rect dst=new Rect(90,155,1510,745);c.drawBitmap(photo,src,dst,p);p.setColor(Color.rgb(195,160,72));p.setStrokeWidth(4);c.drawLine(150,780,1450,780,p);if(handwriting!=null){Rect hs=new Rect(0,0,handwriting.getWidth(),handwriting.getHeight());Rect hd=new Rect(130,805,1470,1060);c.drawBitmap(handwriting,hs,hd,p);}else{p.setColor(Color.rgb(25,35,70));p.setTextSize(38);p.setTextAlign(Paint.Align.LEFT);drawWrapped(c,typed.isEmpty()?"With love on your wedding day ♥":typed,150,845,1300,50,p);}p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.create("serif",Typeface.ITALIC));p.setTextSize(38);p.setColor(Color.rgb(18,40,92));c.drawText("— "+names+" —",W/2,1135,p);return out;}
 private void drawWrapped(Canvas c,String text,float x,float y,float width,float line,Paint p){String[] words=text.split("\\s+");StringBuilder s=new StringBuilder();for(String w:words){String t=s.length()==0?w:s+" "+w;if(p.measureText(t)>width){c.drawText(s.toString(),x,y,p);y+=line;s=new StringBuilder(w);}else{s=new StringBuilder(t);}}if(s.length()>0)c.drawText(s.toString(),x,y,p);}
 private void refreshEntries(){pages.clear();File[] fs=pagesDir.listFiles((d,n)->n.toLowerCase().endsWith(".jpg"));if(fs!=null){Arrays.sort(fs,(a,b)->Long.compare(b.lastModified(),a.lastModified()));pages.addAll(Arrays.asList(fs));}thumbStrip.removeAllViews();for(int i=0;i<pages.size();i++){final int idx=i;ImageView im=new ImageView(this);int w=(int)(150*getResources().getDisplayMetrics().density);int h=(int)(95*getResources().getDisplayMetrics().density);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(w,h);lp.setMargins(6,4,6,4);im.setLayoutParams(lp);im.setScaleType(ImageView.ScaleType.CENTER_CROP);im.setImageURI(Uri.fromFile(pages.get(i)));im.setBackgroundColor(Color.WHITE);im.setPadding(3,3,3,3);im.setOnClickListener(v->showViewer(idx));thumbStrip.addView(im);}findViewById(R.id.emptyHint).setVisibility(pages.isEmpty()?View.VISIBLE:View.GONE);}
 private void showViewer(int idx){if(pages.isEmpty())return;viewingIndex=Math.max(0,Math.min(idx,pages.size()-1));((ImageView)findViewById(R.id.viewerImage)).setImageURI(Uri.fromFile(pages.get(viewingIndex)));showOnly(viewerScreen);findViewById(R.id.prevEntry).setEnabled(viewingIndex>0);findViewById(R.id.nextEntry).setEnabled(viewingIndex<pages.size()-1);}
 private void saveToGallery(File source,String name)throws Exception{ContentValues v=new ContentValues();v.put(MediaStore.Images.Media.DISPLAY_NAME,name);v.put(MediaStore.Images.Media.MIME_TYPE,"image/jpeg");if(Build.VERSION.SDK_INT>=29)v.put(MediaStore.Images.Media.RELATIVE_PATH,"Pictures/GarryKarenWeddingGuestbook");Uri u=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);if(u!=null)try(InputStream in=new FileInputStream(source);OutputStream out=getContentResolver().openOutputStream(u)){byte[] b=new byte[8192];int n;while((n=in.read(b))>0)out.write(b,0,n);}}
 private void copy(File a,File b)throws Exception{try(InputStream in=new FileInputStream(a);OutputStream out=new FileOutputStream(b)){byte[] x=new byte[8192];int n;while((n=in.read(x))>0)out.write(x,0,n);}}
 private void discardPending(){if(pendingPhoto!=null&&pendingPhoto.exists())pendingPhoto.delete();pendingPhoto=null;}
 private void resetToCamera(){discardPending();photoPreview.setImageDrawable(null);photoPreview.setVisibility(View.GONE);reviewControls.setVisibility(View.GONE);countdown.setVisibility(View.GONE);previewView.setVisibility(View.VISIBLE);cameraControls.setVisibility(View.VISIBLE);}
 private void hideSystemUi(){if(Build.VERSION.SDK_INT>=30){WindowInsetsController c=getWindow().getInsetsController();if(c!=null){c.hide(WindowInsets.Type.statusBars()|WindowInsets.Type.navigationBars());c.setSystemBarsBehavior(WindowInsetsController.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE);}}else getWindow().getDecorView().setSystemUiVisibility(5894);}
 @Override protected void onResume(){super.onResume();hideSystemUi();}
}
